force-app/main/default/objects/Opportunity/fields/Internal_Vici_offer_nr__c.field-meta.xml
<CustomField>
    <fullName>Internal_Vici_offer_nr__c</fullName>
    <description>Please fill this field to track Vici&amp;C spa offer documents (if present)
Compilare questo campo per tracciare le offerte dirette vici (se presenti)</description>
    <inlineHelpText>Please fill this field to track Vici&amp;C spa offer documents (if present)
Compilare questo campo per tracciare le offerte dirette vici (se presenti)</inlineHelpText>
    <label>Internal Vici offer nr.</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Validity_internal_offer_if_present__c.field-meta.xml
<CustomField>
    <fullName>Validity_internal_offer_if_present__c</fullName>
    <description>For Vici&amp;C SPA users only
compilare questo campo se è stata emessa un&apos;offerta diretta VICI&amp;C SPA</description>
    <inlineHelpText>For Vici&amp;C SPA users only
compilare questo campo se è stata emessa un&apos;offerta diretta VICI&amp;C SPA</inlineHelpText>
    <label>Validity internal offer if present</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgressivoOffertaInterna__c/ProgressivoOffertaInterna__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Numero progressivo che viene assegnato ad ogni offerta interna. Viene azzerato ogni anno solare.</description>
    <label>ProgressivoOffertaInterna</label>
</CustomObject>

force-app/main/default/objects/ProgressivoOffertaInterna__c/fields/Last__c.field-meta.xml
<CustomField>
    <fullName>Last__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Last</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InternalOfferController_Test.cls
@isTest
private class InternalOfferController_Test {
	@isTest
    static void testAggiornamento() {
        Test.startTest();
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Special';
        opp.CloseDate = Date.today();
        insert opp;
        
        ProgressivoOffertaInterna__c prog = new ProgressivoOffertaInterna__c();
        prog.Last__c = 0;
        insert prog;
        
        InternalOfferController.updateOpportunity(opp.Id);
        
        Test.stopTest();
        
        System.assertEquals(InternalOfferController.leftCode + (String.valueOf(Date.today().year()).mid(2,3)) + '0001',
                            [SELECT Internal_Vici_offer_nr__c FROM Opportunity WHERE Id = :opp.Id].Internal_Vici_offer_nr__c);
        System.assertEquals(1, [SELECT Last__c FROM ProgressivoOffertaInterna__c WHERE Id = :prog.Id].Last__c);
    }
    
    @isTest
    static void testException() {
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Special';
        opp.CloseDate = Date.today();
        opp.Internal_Vici_offer_nr__c = 'QSF' + String.valueOf(Date.today().year()).mid(2,3) + '1';
        opp.Validity_internal_offer_if_present__c = Date.today();
        insert opp;
        
        ProgressivoOffertaInterna__c prog = new ProgressivoOffertaInterna__c();
        prog.Last__c = 0;
        insert prog;
        
        try {
            InternalOfferController.updateOpportunity(opp.Id);
        } catch(InternalOfferController.IntOfferException ex) {
            System.assert(true);
        }
    }
}