force-app/main/default/objects/Opportunity/fields/Internal_Vici_offer_nr__c.field-meta.xml
<CustomField>
    <fullName>Internal_Vici_offer_nr__c</fullName>
    <description>Please fill this field to track Vici&amp;C spa offer documents (if present)
Compilare questo campo per tracciare le offerte dirette vici (se presenti)</description>
    <inlineHelpText>Please fill this field to track Vici&amp;C spa offer documents (if present)
Compilare questo campo per tracciare le offerte dirette vici (se presenti)</inlineHelpText>
    <label>Internal Vici offer nr.</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Validity_internal_offer_if_present__c.field-meta.xml
<CustomField>
    <fullName>Validity_internal_offer_if_present__c</fullName>
    <description>For Vici&amp;C SPA users only
compilare questo campo se è stata emessa un&apos;offerta diretta VICI&amp;C SPA</description>
    <inlineHelpText>For Vici&amp;C SPA users only
compilare questo campo se è stata emessa un&apos;offerta diretta VICI&amp;C SPA</inlineHelpText>
    <label>Validity internal offer if present</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProgressivoOffertaInterna__c/ProgressivoOffertaInterna__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Numero progressivo che viene assegnato ad ogni offerta interna. Viene azzerato ogni anno solare.</description>
    <label>ProgressivoOffertaInterna</label>
</CustomObject>

force-app/main/default/objects/ProgressivoOffertaInterna__c/fields/Last__c.field-meta.xml
<CustomField>
    <fullName>Last__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Last</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InternalOfferController.cls
public class InternalOfferController {
    @TestVisible private static String leftCode = 'QSF';
	public class IntOfferException extends Exception {}
	
    @AuraEnabled
    public static void updateOpportunity(Id opportunityId) {
        Opportunity opp = [SELECT Internal_Vici_offer_nr__c, Validity_internal_offer_if_present__c
                           FROM Opportunity
                   		   WHERE Id = :String.escapeSingleQuotes(opportunityId)
                           LIMIT 1];
        
        if (opp.Internal_Vici_offer_nr__c == NULL && opp.Validity_internal_offer_if_present__c == NULL) {
            ProgressivoOffertaInterna__c cs = [SELECT Last__c FROM ProgressivoOffertaInterna__c];
            String yearCode = String.valueOf(Date.today().year()).mid(2, 3);
            
            System.debug('Prog. code: ' + String.valueOf(cs.Last__c+1).leftPad(4, '0'));
            
            opp.Internal_Vici_offer_nr__c = leftCode + yearCode + (String.valueOf(++cs.Last__c).leftPad(4, '0'));
            opp.Validity_internal_offer_if_present__c = Date.today().addDays(60);
            
            update cs;
            update opp;
        } else {
            throw new IntOfferException('The fields are already enhanced');
        }
    }
}