force-app/main/default/objects/ProgressivoOffertaInterna__c/ProgressivoOffertaInterna__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Numero progressivo che viene assegnato ad ogni offerta interna. Viene azzerato ogni anno solare.</description>
    <label>ProgressivoOffertaInterna</label>
</CustomObject>

force-app/main/default/objects/ProgressivoOffertaInterna__c/fields/Last__c.field-meta.xml
<CustomField>
    <fullName>Last__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Last</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ResettaProgressivoOffertaInterna.cls
global class ResettaProgressivoOffertaInterna implements Schedulable{
    private final static String sch = '0 0 0 1 JAN ? ';
    private final String jobName;
    
    global ResettaProgressivoOffertaInterna(String jobName) {
        this.jobName = jobName;
    }
    global void execute(SchedulableContext sc) {
        ProgressivoOffertaInterna__c cs = [SELECT Last__c FROM ProgressivoOffertaInterna__c];
        cs.Last__c = 0;
        update cs;
        ResettaProgressivoOffertaInterna p = new ResettaProgressivoOffertaInterna(this.jobName);
        
        String newDate = sch + (Date.today().year()+1);
        System.debug('newDate: '+newDate);
        if (sc.getTriggerId() != NULL) System.abortJob(sc.getTriggerId());
        System.schedule(jobName, newDate, p);
    }
}