force-app/main/default/objects/Column_Dealer_Portal__c/Column_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Column Dealer Portal</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns Dealer Portal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Column_Dealer_Portal__c/fields/Field_Dealer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Field_Dealer_Portal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Dealer Portal</label>
    <referenceTo>Field_Dealer_Portal__c</referenceTo>
    <relationshipLabel>Columns Dealer Portal</relationshipLabel>
    <relationshipName>Columns_Dealer_Portal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Column_Dealer_Portal__c/fields/Table_Dealer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Table_Dealer_Portal__c</fullName>
    <label>Table Dealer Portal</label>
    <referenceTo>Table_Dealer_Portal__c</referenceTo>
    <relationshipLabel>Columns Dealer Portal</relationshipLabel>
    <relationshipName>Columns_Dealer_Portal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/isBlocked__c.field-meta.xml
<CustomField>
    <fullName>isBlocked__c</fullName>
    <formula>IF( Login_Error_Count__c &gt; 3, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isBlocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/isReadOnly__c.field-meta.xml
<CustomField>
    <fullName>isReadOnly__c</fullName>
    <formula>true</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isReadOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Succesfully_Login__c.field-meta.xml
<CustomField>
    <fullName>Last_Succesfully_Login__c</fullName>
    <label>Last Succesfully Login</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Login_Error_Count__c.field-meta.xml
<CustomField>
    <fullName>Login_Error_Count__c</fullName>
    <label>Login Error Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password Dealer Portal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/resetPwdDealer__c.field-meta.xml
<CustomField>
    <fullName>resetPwdDealer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>resetPwdDealer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username Dealer Portal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Dealer_Portal__c/Field_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Field Dealer Portal</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields Dealer Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Dealer_Portal__c/fields/isReadOnly__c.field-meta.xml
<CustomField>
    <fullName>isReadOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isReadOnly</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Field_Dealer_Portal__c/fields/Key_Field__c.field-meta.xml
<CustomField>
    <fullName>Key_Field__c</fullName>
    <externalId>true</externalId>
    <label>Key Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Dealer_Portal__c/Form_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Form Dealer Portal</label>
    <nameField>
        <label>Form Dealer Portal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms Dealer Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Dealer_Portal__c/fields/Key_Form__c.field-meta.xml
<CustomField>
    <fullName>Key_Form__c</fullName>
    <externalId>true</externalId>
    <label>Key Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Dealer_Portal__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <label>SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Row_Dealer_Portal__c/Row_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Row Dealer Portal</label>
    <nameField>
        <label>Row Dealer Portal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rows Dealer Portal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Row_Dealer_Portal__c/fields/Field_Dealer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Field_Dealer_Portal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Dealer Portal</label>
    <referenceTo>Field_Dealer_Portal__c</referenceTo>
    <relationshipLabel>Rows Dealer Portal</relationshipLabel>
    <relationshipName>Rows_Dealer_Portal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Row_Dealer_Portal__c/fields/Form_Dealer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Form_Dealer_Portal__c</fullName>
    <label>Form Dealer Portal</label>
    <referenceTo>Form_Dealer_Portal__c</referenceTo>
    <relationshipLabel>Rows Dealer Portal</relationshipLabel>
    <relationshipName>Rows_Dealer_Portal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Row_Dealer_Portal__c/fields/isSection__c.field-meta.xml
<CustomField>
    <fullName>isSection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Row_Dealer_Portal__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Row_Dealer_Portal__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Table_Dealer_Portal__c/Table_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Table Dealer Portal</label>
    <nameField>
        <label>Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables Dealer Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Table_Dealer_Portal__c/fields/Key_Table__c.field-meta.xml
<CustomField>
    <fullName>Key_Table__c</fullName>
    <externalId>true</externalId>
    <label>Key Table</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Table_Dealer_Portal__c/fields/SOQL_2__c.field-meta.xml
<CustomField>
    <fullName>SOQL_2__c</fullName>
    <label>SOQL 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Table_Dealer_Portal__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <label>SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/cPortaleRivenditori.cls
global class cPortaleRivenditori {
    @RemoteAction
    global static String doLogin(String username, String password) 
    {
        system.debug(username);
        system.debug(password);
        
        List<Contact> lc=[select id, accountId, Username__c, Password__c , Login_Error_Count__c, Last_Succesfully_Login__c from Contact where username__c=:username and isBlocked__c=false];
        
        if (lc.size()>0)
        {            
            if (lc[0].password__c==password) {
                lc[0].Last_Succesfully_Login__c=DateTime.now();
                lc[0].Login_Error_Count__c=0;
                update lc[0]; 
                return lc[0].accountId;
            } else
            {
                // wrong password
                if (lc[0].Login_Error_Count__c!=null)
                    lc[0].Login_Error_Count__c++;
                else
                    lc[0].Login_Error_Count__c=1;
                update lc[0]; 
                return null;
            }
            
        } else return null;
        
    }
    
    @RemoteAction
    global static String sendEmailForgetPwd(String email ) 
    {
        system.debug(email);        
        List<Contact> lc=[select id, accountId, Email , Username__c, Password__c , resetPwdDealer__c , Login_Error_Count__c, Last_Succesfully_Login__c from Contact where Email=:email ];
        
        if (lc.size()>0)
        {    
            
            lc[0].resetPwdDealer__c=true;
            update lc[0]; 
            return 'Email Send';
            
        } else return null;
        
    }
    
    
    
    
    @RemoteAction
    global static String uploadAttachment(String parentId, String filename, String payload )
    {
        Attachment att=new Attachment();
        att.Name=filename;
        if (att.Name=='') att.Name='untitled';
        att.ParentId=parentId;
        att.Body=EncodingUtil.base64Decode(payload);
        system.debug(att);
        
        insert att;
        
        return 'File Caricato con successo';
    }
    
    
    @RemoteAction
    global static List<Attachment> getAttachment (String parentid)
    {
        List <Attachment> attachment = [select id, name, Description, OwnerId , BodyLength, CreatedDate from Attachment where parentId=:parentid order by CreatedDate desc];
        return attachment;
    }
    
    
    global class fieldType
    {
        string oggetto;
        string name;
        string label;
        string format;
        integer size;
        integer size2;
        string values;
        string labels;
    }
    
    
    @RemoteAction
    global static List<fieldType> getCampi(List<String> oggetti)
    {
        
        // nome, tipo, size, size2, valori
        List<fieldType> lf=new List<fieldType>();
        
        for (String oggetto: oggetti) {
            Schema.SObjectType targetType = Schema.getGlobalDescribe().get(oggetto);
            Schema.DescribeSObjectResult dsr = targetType.getDescribe();
            
            for (Schema.SObjectField sof:dsr.fields.getMap().values())
            {
                Schema.DescribeFieldResult dfr=sof.getDescribe();
                Schema.DisplayType dt = dfr.getType(); 
                
                fieldType ft=new fieldType();
                ft.oggetto=oggetto;
                ft.name=dfr.getName();
                ft.label=dfr.getLabel();
                ft.size=dfr.getLength();
                ft.size2=dfr.getScale();
                
                //system.debug(ft.name);
                //system.debug(ft.label);
                
                if (dt==Schema.DisplayType.Boolean)         ft.format='Boolean';
                if (dt==Schema.DisplayType.Date)            ft.format='Date';
                if (dt==Schema.DisplayType.Currency )       ft.format='Currency';
                if (dt==Schema.DisplayType.String )         ft.format='String';
                if (dt==Schema.DisplayType.TextArea )       ft.format='TextArea';
                if (dt==Schema.DisplayType.picklist )       ft.format='Picklist';
                if (dt==Schema.DisplayType.multipicklist )  ft.format='MultiPicklist';
                
                ft.values='';
                ft.labels='';

                List<Schema.PicklistEntry> lpe = dfr.getPicklistValues();
                for (Schema.PicklistEntry pe:lpe)
                {  
                    ft.labels+=pe.getLabel()+';';
                    ft.values+=pe.getValue()+';';
                }
                
                
                //system.debug(ft.values);
                lf.add(ft);
            }
        }
        
        return lf;        
        
        
    }

    @RemoteAction
    global static map <string, List <LIst <sObject>>> getDati(List<String> oggetti,  String idDealer) 
    {
        system.debug(idDealer);
        List <Table_Dealer_Portal__c> ltd = [Select Name, Key_Table__c , SOQL__c , SOQL_2__c  From Table_Dealer_Portal__c WHERE Name=:oggetti ];
        system.debug(ltd);
        map <string, List <LIst <sObject>>> mappa = new  map <string, List <LIst <sObject>>>();
        if (ltd.size()>0)
        {
            for (Table_Dealer_Portal__c tdp:ltd) {
                List <LIst <sObject>> lista = new List <LIst <sObject>>();
                String query = '';
                String target = '$id';
                if (tdp.SOQL__c.contains(target)) query = tdp.SOQL__c.replace(target,idDealer);
                else query = tdp.SOQL__c;
                
                system.debug(query);
                LIst <sObject> llr = database.query(query);
                lista.add(llr);
                
                //da rivedere SOQL2
                /*
                if (tdp.SOQL_2__c!=null && tdp.SOQL_2__c!='') {
                LIst <sObject> llr2 = database.query(tdp.SOQL_2__c);
                lista.add(llr2);
                }
                
                */
                
                mappa.put(tdp.name,lista);
            }
        }
        return mappa;
    }
    
    @RemoteAction
    global static sObject getDatiForm(String oggetto, String idOggetto) 
    {
        system.debug(oggetto); 
        system.debug(idOggetto); 
        List <Form_Dealer_Portal__c > ltd = [Select Name, Key_Form__c , SOQL__c  From Form_Dealer_Portal__c  WHERE Name=:oggetto ];
        system.debug(ltd);        
        if (ltd.size()>0)
        {
            String query = ltd[0].SOQL__c + ' WHERE Id= \'' + idOggetto +'\' ';
            system.debug(query); 
            
            sObject obj = database.query(query);
            
            return obj;
        }
        
        return null;
    }
    
    @RemoteAction
    global static List <Column_Dealer_Portal__c> getConfigurazioneCampi(List<String> oggetti) 
    {
        
        List <Column_Dealer_Portal__c> llr = [Select Field_Dealer_Portal__r.Id, Table_Dealer_Portal__r.Name, Order__c, Field_Dealer_Portal__r.Key_Field__c, Field_Dealer_Portal__r.Name,  
                                              Field_Dealer_Portal__r.Label__c, Field_Dealer_Portal__r.Type__c, Field_Dealer_Portal__r.Value__c , Field_Dealer_Portal__r.isReadOnly__c , Field_Dealer_Portal__r.isRequired__c 
                                              from Column_Dealer_Portal__c  
                                              where Table_Dealer_Portal__r.Name=:oggetti order by Order__c];
        return llr;
    }
    
    @RemoteAction
    global static List <Row_Dealer_Portal__c> getConfigurazioneCampiForm(List<String> oggetti) 
    {
        
        List <Row_Dealer_Portal__c> llr = [Select Name, Field_Dealer_Portal__r.Id, Form_Dealer_Portal__r.Name, Order__c, Field_Dealer_Portal__r.Key_Field__c, Field_Dealer_Portal__r.Name,  
                                           Field_Dealer_Portal__r.Label__c, Field_Dealer_Portal__r.Type__c, Field_Dealer_Portal__r.Value__c , isSection__c  , Position__c , Section__c , Field_Dealer_Portal__r.isReadOnly__c , Field_Dealer_Portal__r.isRequired__c 
                                           from Row_Dealer_Portal__c   
                                           where Form_Dealer_Portal__r.Name=:oggetti order by Section__c , Order__c, Position__c];
        return llr;
    }
    
    @RemoteAction
    global static sobject saveRowTable (String oggettoNome, sobject riga) 
    {   
        system.debug(riga);
        upsert riga ;
        return riga;
    }

    /*
    
    @RemoteAction
    global static String deleteRowTable (String idRow) 
    {   
        system.debug(idRow);
        
        list <Opportunity> lo = [select id from Opportunity where id=:idRow];
        
        delete lo;
        return idRow;
    }
	*/
    
}