force-app/main/default/objects/Column_Dealer_Portal__c/Column_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Column Dealer Portal</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns Dealer Portal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Column_Dealer_Portal__c/fields/Field_Dealer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Field_Dealer_Portal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Dealer Portal</label>
    <referenceTo>Field_Dealer_Portal__c</referenceTo>
    <relationshipLabel>Columns Dealer Portal</relationshipLabel>
    <relationshipName>Columns_Dealer_Portal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Column_Dealer_Portal__c/fields/Table_Dealer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Table_Dealer_Portal__c</fullName>
    <label>Table Dealer Portal</label>
    <referenceTo>Table_Dealer_Portal__c</referenceTo>
    <relationshipLabel>Columns Dealer Portal</relationshipLabel>
    <relationshipName>Columns_Dealer_Portal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password Dealer Portal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username Dealer Portal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Field_Dealer_Portal__c/Field_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Field Dealer Portal</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields Dealer Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_Dealer_Portal__c/fields/Key_Field__c.field-meta.xml
<CustomField>
    <fullName>Key_Field__c</fullName>
    <externalId>true</externalId>
    <label>Key Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Dealer_Portal__c/Form_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Form Dealer Portal</label>
    <nameField>
        <label>Form Dealer Portal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms Dealer Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Dealer_Portal__c/fields/Key_Form__c.field-meta.xml
<CustomField>
    <fullName>Key_Form__c</fullName>
    <externalId>true</externalId>
    <label>Key Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Form_Dealer_Portal__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <label>SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Potential customer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Potential dealer</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Sub-dealer</fullName>
            </value>
            <value>
                <fullName>Finder or Rep.</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Not suitable for MTL</fullName>
            </value>
            <value>
                <fullName>Not suitable for Metrios</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Row_Dealer_Portal__c/Row_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Row Dealer Portal</label>
    <nameField>
        <label>Row Dealer Portal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rows Dealer Portal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Row_Dealer_Portal__c/fields/Field_Dealer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Field_Dealer_Portal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Field Dealer Portal</label>
    <referenceTo>Field_Dealer_Portal__c</referenceTo>
    <relationshipLabel>Rows Dealer Portal</relationshipLabel>
    <relationshipName>Rows_Dealer_Portal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Row_Dealer_Portal__c/fields/Form_Dealer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Form_Dealer_Portal__c</fullName>
    <label>Form Dealer Portal</label>
    <referenceTo>Form_Dealer_Portal__c</referenceTo>
    <relationshipLabel>Rows Dealer Portal</relationshipLabel>
    <relationshipName>Rows_Dealer_Portal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Table_Dealer_Portal__c/Table_Dealer_Portal__c.object-meta.xml
<CustomObject>
    <label>Table Dealer Portal</label>
    <nameField>
        <label>Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables Dealer Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Table_Dealer_Portal__c/fields/Key_Table__c.field-meta.xml
<CustomField>
    <fullName>Key_Table__c</fullName>
    <externalId>true</externalId>
    <label>Key Table</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Table_Dealer_Portal__c/fields/SOQL_2__c.field-meta.xml
<CustomField>
    <fullName>SOQL_2__c</fullName>
    <label>SOQL 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Table_Dealer_Portal__c/fields/SOQL__c.field-meta.xml
<CustomField>
    <fullName>SOQL__c</fullName>
    <label>SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/tcPortaleRivenditori.cls
@isTest
public class tcPortaleRivenditori 
{
	testMethod static void testMe()
    {
        Lead l=new Lead(Lastname='prova', Company='prova', Country='Italy');
        insert l;
        
        l.Country = 'Albania';
        update l;
        
        Account a=new Account(name='prova');
        insert a;
        
        Contact c=new Contact(AccountId=a.id, lastname='prova', username__c='u', Password__c='p', email='prova@prova.it');
        insert c;
        
        
        cPortaleRivenditori.saveRowTable('Lead', l);
        
        cPortaleRivenditori.doLogin('u','p');
        cPortaleRivenditori.doLogin('u','p1');
        cPortaleRivenditori.doLogin('u1','p1');

        cPortaleRivenditori.sendEmailForgetPwd('prova@prova.it');
        cPortaleRivenditori.sendEmailForgetPwd('test@prova.it');
        
//        Attachment att=new Attachment(parentId=a.id, name='prova', body=blob.valueOf('prova'));
        cPortaleRivenditori.uploadAttachment(a.id, 'prova', 'prova');

        cPortaleRivenditori.getAttachment (a.id);
//        cPortaleRivenditori.fieldType ft=new cPortaleRivenditori.fieldType();
//        ft.oggetto='prova';
        
        List<String> oggetti=new List<String>();
        oggetti.add('Lead');
        
        cPortaleRivenditori.getCampi(oggetti);

        Field_Dealer_Portal__c f1=new Field_Dealer_Portal__c();
        f1.Key_Field__c='Lead.LastName';
        f1.type__c='text';
        f1.Label__c='LastName';
        insert f1;
        
        Table_Dealer_Portal__c t1=new Table_Dealer_Portal__c();
        t1.Name='t1';
        t1.Key_Table__c='t1';
        t1.soql__c='select id, lastname from lead';
        t1.soql_2__c='select id, lastname from lead';
        insert t1;

        Column_Dealer_Portal__c c1=new Column_Dealer_Portal__c();
        c1.Table_Dealer_Portal__c=t1.id;
        c1.Field_Dealer_Portal__c=f1.id;
        c1.Order__c=1;
        insert c1;
        
        
        Form_Dealer_Portal__c fo1=new Form_Dealer_Portal__c();
        fo1.Name='fo1';
        fo1.Key_Form__c ='fo1';
        fo1.soql__c='select id, lastname from lead';
        insert fo1;

        Row_Dealer_Portal__c r1=new Row_Dealer_Portal__c();
        r1.Form_Dealer_Portal__c =fo1.id;
        r1.Field_Dealer_Portal__c=f1.id;
            
        cPortaleRivenditori.getConfigurazioneCampi(oggetti);
        
        cPortaleRivenditori.getConfigurazioneCampiForm(oggetti);

        
        List<String> lo=new List<String>();
        lo.add('t1');

        Map<String, List< List<sObject>>> m=cPortaleRivenditori.getDati( lo, a.id );
        
        cPortaleRivenditori.getDatiForm('fo1', l.id);
        cPortaleRivenditori.getDatiForm('xxx', l.id);
        
        /*
    global static Map <String,sobject>  saveRowTable (Map <String,sobject> mappa, String nomeOggetto, boolean updt) 

		*/
    }
       
}